/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package poo;
import java.util.ArrayList;


public class App { 
   

    public static void main(String[] args) {
        ArrayList<Veiculo>veiculo=new ArrayList<>();
        veiculo.add(new Ferrari());
        veiculo.add(new Pampa());
        veiculo.add(new Panther());

        //com a pampa acelerada


        for(Veiculo V:veiculo){
            if(V instanceof Ferrari){
                ((Ferrari) V).acelerar(30);
                if(((Ferrari) V).abrirCapota())
                System.out.println(((Ferrari) V).abrirCapota()+" capota aberta");
                ((Ferrari) V).acelerar(40);
                ((Ferrari) V).setLastro(10);

                System.out.println(((Ferrari) V).abrirCapota()+" capota fechada");
            }
            else if(V instanceof Pampa){
                ((Pampa) V).acelerar(12);
                ((Pampa) V).abrirCacamba();
                if( ((Pampa) V).abrirCacamba()==false){
                    System.out.println("Pampa: Não foi possivel abrir a caçamba, carro em movimento");
                }else{
                    System.out.println("Pampa: capota aberta");      
                } 
        
                      
                if( ((Pampa) V).ativarDesativarTracao()==false){
                    System.out.println("Pampa: Não foi possivel ativar 4x4, carro em movimento");
                }else{
                    System.out.println("Pampa: 4x4 ativa");      
                }    

                 //freando a pampa
                 ((Pampa) V).frear(12);
                 ((Pampa) V).abrirCacamba();
                    if(((Pampa) V).abrirCacamba()==false){
                        System.out.println("Pampa: Não foi possivel abrir a capota, carro em movimento");
                 }else{
                         System.out.println("Pampa: capota aberta");      
                        } 

                if( ((Pampa) V).ativarDesativarTracao()==false){
                        System.out.println("Pampa: Não foi possivel ativar 4x4, carro em movimento");
                }else{
                        System.out.println("Pampa: 4x4 ativa");      
                }       


            } else if(V instanceof Panther){

                //teste com a Panther
                ((Panther) V).acelerar(100);
                ((Panther) V).abrirRodas();
                if(((Panther) V).ativarDesativarTracao()==false){
                    System.out.println("Panther: Não foi possivel ativar 4x4, carro em movimento");
                }else{
                    System.out.println("Panther: 4x4 ativa");      
                } 
                //teste com a Panther freada
                ((Panther) V).frear(100);
                ((Panther) V).abrirRodas();
                if(((Panther) V).ativarDesativarTracao()==false){
                    System.out.println("Panther: Não foi possivel ativar 4x4, carro em movimento");
                }else{
                    System.out.println("Panther: 4x4 ativa");      
                } 

                
            }

           

        }    
    }
}       
       
     

